# Site Settings
source: .
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor", ".git"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/
remote_theme: yizeng/jekyll-theme-simple-texture

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
#excerpt_separator: <!--more-->
markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: SingularityKChen
description: "This is the blog of SingularityKChen"
keywords: 'HardWare,Chisel,Digital Design'
author:
  name: Chen, Chunyun
  job_title:
  location:
  email: chency_singularity@163.com
  social_links:
    - name: github
      url: https://github.com/SingularityKChen
    - name: linkedin
      url: https://www.linkedin.com/in/singularitykchen/
    - name: facebook
      url:
    - name: instagram
      url:
    - name: stackoverflow
      url:
    - name: twitter
      url: 
    - name: vk
      url:
home:
  section1: <h1>SingularityKChen</h1>
  section2: <h2>I am a slow walker, but I never walk back.</h2>
  section3: <div class="social-links"><a class="ico-github btn" href="https://github.com/SingularityKChen" title="View on GitHub"></a></div>
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License of your choice.
  cc_license_image: /assets/images/theme/cc-by-sa.png # An image of your CC License. 
  footer_content: A gem-based responsive simple texture styled <a href="http://jekyllrb.com/">Jekyll</a> theme.

disqus:
  shortname: singularitykchen
  public_key: # e.g. ULZ0b9TFefCUJHKQd4JCKv2v3u27YoG7YG8zXPewkWrT333Z0Se9YnxLzoV6VM8W
google_tag_manager: # e.g. 'GTM-KCQJXZ8F'
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/. E.g. ra-53329e27694534j5 

gitment:
  owner: singularitykchen
  repo: https://github.com/SingularityKChen/singularitykchen.github.io
  client_id: d22349012c96f951207c
  client_secret: 843195c3b1f0b2f258f88684767445c2ceae1996

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: SingularityKChen
      excerpt: There is no thing to show~
      comments: true